FROM gitlab.kitware.com:4567/keu-computervision/slam/ros2_env
LABEL maintainer="Julia Sanchez julia.sanchez@kitware.com"

WORKDIR /root

RUN /ros_entrypoint.sh

# Install SLAM
COPY install_slam.bash install_slam.bash
RUN bash install_slam.bash
RUN rm install_slam.bash

RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
RUN echo "source /root/slam/install/setup.bash" >> ~/.bashrc

COPY slam_entrypoint.bash slam_entrypoint.bash
ENTRYPOINT ["bash", "slam_entrypoint.bash"]