FROM osrf/ros:humble-desktop-full
LABEL maintainer="Julia Sanchez julia.sanchez@kitware.com"

# Install Slam ROS dependencies
RUN apt update
RUN apt install -y ros-$ROS_DISTRO-libg2o
RUN apt install -y ros-$ROS_DISTRO-velodyne

# Install Slam dependencies
COPY deps_install_scripts/install_deps.sh install_deps.sh
RUN sh install_deps.sh

COPY deps_install_scripts/install_ceres.sh install_ceres.sh
RUN sh install_ceres.sh

COPY deps_install_scripts/install_nanoflann.sh install_nanoflann.sh
RUN sh install_nanoflann.sh

# Graphic display on host
RUN apt -y install libgl1-mesa-glx libgl1-mesa-dri

# Erase apt cache
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /root